config/routes.rb
Rails.application.routes.draw do
  root 'lunches#new'
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  resources :lunches, only: %i(index create destroy)
  resources :members, except: :show
  resources :projects, expect: :show
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :assignment, dependent: :destroy
  has_many :members, through: :assignment

  validates :name, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i(edit update destroy)

  def index
    @projects = Project.all
  end

  def show
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      flash[:success] = t('dictionary.message.create.complete', resource_name: @project.name)
      redirect_to projects_url
    else
      render :new
    end
  end

  def update
    if @project.update(project_params)
      flash[:success] = t('dictionary.message.update.complete', resource_name: @project.name)
      redirect_to projects_url
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    flash[:danger] = t('dictionary.message.destroy.complete', resource_name: @project.name)
    redirect_to projects_url
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name)
  end
end

app/views/projects/_form.html.slim
= form_for @project do |f|
  - if @project.errors.any?
    .text-danger
      ul
        - @project.errors.full_messages.each do |message|
          li = message

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  = f.submit id: 'submit-btn', class: 'btn btn-primary'

- if @project.persisted?
  hr
  = link_to '削除する', @project, data: { confirm: @project.delete_confirm }, method: :delete, class: 'btn btn-outline-danger'

app/views/projects/edit.html.slim
h3.my-3 プロジェクト編集

= render 'form'

app/views/projects/index.html.slim
h3.my-3 プロジェクト
.card.my-3
  .card-body
    = link_to new_project_path, id: 'new-btn', class: 'btn btn-outline-primary'
      | プロジェクト追加

    table.table.border-bottom.my-3
      thead.thead-light
        tr
          th = Project.human_attribute_name(:name)
          th

      tbody
        - @projects.each do |project|
          tr
            td = project.name
            td
              = link_to '編集', edit_project_path(project), class: 'btn btn-outline-primary'

app/views/projects/new.html.slim
h3.my-3 プロジェクト追加

== render 'form'