config/routes.rb
Rails.application.routes.draw do
  root 'lunches#new'
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  resources :lunches, only: %i(index create destroy)
  resources :members, except: :show
  resources :projects, expect: :show
end

app/models/lunch.rb
class Lunch < ApplicationRecord
  belongs_to :created_by, foreign_key: :user_id, class_name: 'User'
  belongs_to :quarter
  has_and_belongs_to_many :members

  validate :must_go_to_lunch_with_members_who_did_not_go_together_during_same_quarter

  def label_with_date_and_member_names
    "#{date} #{members.pluck(:real_name).join(',')}の給付金利用履歴"
  end

  private

  # 同じクォーター内で同じメンバーの組み合わせでランチに行ってないことを検証
  def must_go_to_lunch_with_members_who_did_not_go_together_during_same_quarter
    lunches_in_same_quarter = Lunch.includes(:members).where(quarter: quarter)
    lunches_in_same_quarter.each do |lunch|
      members_who_went_to_lunch_together = lunch.members & self.members
      if members_who_went_to_lunch_together.size >= 2
        message = "#{members_who_went_to_lunch_together.map(&:real_name).join(',')}は#{lunch.date}にランチ済みです"
        errors.add(:went_to_lunch_with_same_members, message)
      end
    end
  end
end

app/models/lunch_form.rb
class LunchForm
  include ActiveModel::Model

  attr_accessor :date, :members

  validates :date, presence: {message: '日付を入力してください'}
  validate :date_must_be_in_the_past, if: -> { date.present? }
  validate :must_have_benefits_available_count_members
  validate :members_should_exist

  BENEFITS_AVAILABLE_MEMBERS_COUNT = 3

  def date_must_be_in_the_past
    return if date.to_date <= Date.current

    errors.add(:date, '今日までの日付を入力してください')
  end

  # 規定人数が満たされていること
  def must_have_benefits_available_count_members
    return if members.count(&:present?) == BENEFITS_AVAILABLE_MEMBERS_COUNT

    errors.add(:members, "#{BENEFITS_AVAILABLE_MEMBERS_COUNT}人のメンバーを入力してください")
  end

  # 実在する member が指定されていること
  def members_should_exist
    return if Member.where(real_name: members).count == members.count

    errors.add(:members, '存在する名前を入力してください')
  end
end

app/controllers/lunches_controller.rb
class LunchesController < ApplicationController
  def index
    @quarters = Quarter.includes(lunches: %i(lunches_members members created_by))
      .order('quarters.start_date', 'lunches.date desc', 'members.created_at')
  end

  def new
    set_variables_for_new_lunch_view
    @lunch_form = LunchForm.new
  end

  def create
    @lunch_form = LunchForm.new(lunch_form_params)

    if @lunch_form.valid?
      lunch = create_lunch_with_quarter(@lunch_form)
      flash[:success] = t('dictionary.message.create.complete', resource_name: lunch.label_with_date_and_member_names)
      redirect_to lunches_url
    else
      set_variables_for_new_lunch_view
      render :new
    end
  end

  def destroy
    @lunch = Lunch.find(params[:id])

    if @lunch.created_by == current_user
      resource_name = @lunch.label_with_date_and_member_names
      @lunch.destroy
      flash[:danger] = t('dictionary.message.destroy.complete', resource_name: resource_name)
    else
      flash[:warning] = '削除対象となったランチはあなたが作成したものではないので削除できませんでした'
    end
    redirect_to lunches_url
  end

  private

  def lunch_form_params
    params.require(:lunch_form).permit(:date, members: [])
  end

  def set_variables_for_new_lunch_view
    @members = Member.includes(:projects).where(retired: false).order(:created_at)
    gon.lunch_trios = Quarter.current_quarter.lunches.includes(:members).map(&:members)
    gon.login_member = Member.find_by(email: current_user.email)
  end

  def create_lunch_with_quarter(lunch_form)
    members = Member.where(real_name: lunch_form.members)
    date = lunch_form.date.to_date
    quarter = Quarter.find_or_create_quarter(date)
    quarter.lunches.create!(date: date, members: members, created_by: current_user)
  end
end

app/views/lunches/index.html.slim
h3.my-3 ランチ履歴の一覧

.card
  .card-body
    ul.nav.nav-pills role="tablist"
      - @quarters.each do |quarter|
        li.nav-item
          a.nav-link class=current_quarter_active(quarter) data-toggle="pill" href="#period#{quarter.period}-#{quarter.ordinal}"
            div data-toggle="tooltip" title="#{quarter.start_date} ~ #{quarter.end_date}"
              = "#{quarter.period}期-#{quarter.ordinal}Q"

    .tab-content.mt-1
      - @quarters.each do |quarter|
        .tab-pane class=current_quarter_active(quarter) id="period#{quarter.period}-#{quarter.ordinal}"
          table.table.border-bottom
            thead.thead-light
              tr
                th = Lunch.human_attribute_name(:date)
                th = Lunch.human_attribute_name(:members)
                th
            tbody
              - quarter.lunches.each do |lunch|
                tr
                  td = lunch.date
                  td
                    button.mx-3.btn.btn-outline-secondary.clipboard-btn data-clipboard-text="#{lunch.members.pluck(:real_name).join(',')}"
                      = icon('far', 'copy')
                    .d-inline
                      = lunch.members.pluck(:real_name).join(',')
                  td
                    - if lunch.created_by == current_user
                      = link_to '削除', lunch, data: { confirm: t('dictionary.message.destroy.confirm', resource_name: lunch.label_with_date_and_member_names) }, method: :delete, class: 'btn btn-outline-danger'

app/views/lunches/new.html.slim
h3.my-3 ランチ履歴の登録

.card
  .card-body
    p.text-primary ランチに行く (行った) メンバーを下から3人選んで登録してください。
    .row
      .col-8
        #members-list
          table.table.border#members-table
            thead.thead-light
              tr
                th = Member.human_attribute_name(:real_name)
                th = Member.human_attribute_name(:projects)
                th 選べない理由
            tbody
              - @members.each do |member|
                tr.member-row
                  td.member-name = member.real_name
                  td.member-project = member.projects.pluck(:name).join(',')
                  td.unselectable-reason

      .col-4
        = form_with model: @lunch_form, url: lunches_path, local: true, class: 'lunch-form' do |f|
          - if @lunch_form.errors.any?
            .text-danger
              ul
                - @lunch_form.errors.messages.each do |attr, messages|
                  li = messages.first
          .form-group
            = f.label :member, '１人目', value: 'first'
            div data-toggle="tooltip" title="クリックで選択が戻ります"
              = f.text_field :member, name: 'lunch_form[members][]', readonly: true, onfocus: "this.blur();", id: 'lunch_form_member_first', class: 'form-control form-control-lg member-form'
          .form-group
            = f.label :member, '２人目', value: 'second'
            div data-toggle="tooltip" title="クリックで選択が戻ります"
              = f.text_field :member, name: 'lunch_form[members][]', readonly: true, onfocus: "this.blur();", id: 'lunch_form_member_second', class: 'form-control form-control-lg member-form'
          .form-group
            = f.label :member, '３人目', value: 'third'
            div data-toggle="tooltip" title="クリックで選択が戻ります"
              = f.text_field :member, name: 'lunch_form[members][]', readonly: true, onfocus: "this.blur();", id: 'lunch_form_member_third', class: 'form-control form-control-lg member-form'
          .form-group
            = f.label :date, '行った日'
            = f.date_field :date, value: Date.current, max: Date.current, class: 'form-control'
          .text-center
            = f.submit class: 'btn btn-primary btn-lg'