config/routes.rb
Rails.application.routes.draw do
  root 'lunches#new'
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  resources :lunches, only: %i(index create destroy)
  resources :members, except: :show
  resources :projects, expect: :show
end

app/models/member.rb
class Member < ApplicationRecord
  has_many :assignments, dependent: :destroy
  has_many :projects, through: :assignments
  has_and_belongs_to_many :lunches
  validates :email, uniqueness: true, allow_nil: true
  validates :handle_name, presence: true
  validates :real_name, presence: true
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: %i(edit update destroy)

  def index
    @members = Member.includes(:projects).order(:created_at)
  end

  def new
    @member = Member.new
  end

  def edit
  end

  def create
    @member = Member.new(member_params)

    if @member.save
      flash[:success] = t('dictionary.message.create.complete', resource_name: @member.real_name)
      redirect_to members_url
    else
      render :new
    end
  end

  def update
    if @member.update(member_params)
      flash[:success] = t('dictionary.message.update.complete', resource_name: @member.real_name)
      redirect_to members_url
    else
      render :edit
    end
  end

  def destroy
    @member.destroy
    flash[:danger] = t('dictionary.message.destroy.complete', resource_name: @member.real_name)
    redirect_to members_url
  end

  private

  def set_member
    @member = Member.find(params[:id])
  end

  def member_params
    params.require(:member).permit(:handle_name, :real_name, :retired, :email, project_ids: [])
  end
end

app/views/members/_form.html.slim
= form_for @member do |f|
  - if @member.errors.any?
    .text-danger
      ul
        - @member.errors.full_messages.each do |message|
          li = message

  .form-group
    = f.label :handle_name
    = f.text_field :handle_name, class: 'form-control'
  .form-group
    = f.label :real_name
    = f.text_field :real_name, class: 'form-control'
  .field.input-field
    = f.label :email
    = f.email_field :email, class: 'form-control'
  .form-group
    = f.label :project_ids, 'プロジェクト'
    = f.collection_select :project_ids, Project.all, :id, :name, {} ,{multiple: true, class: 'form-control js-searchable'}
  - if @member.persisted?
    .form-group.form-check
      = f.check_box :retired, class: 'form-check-input filled-in'
      = f.label :retired, '退職済み', class: 'form-check-label'

  = f.submit id: 'submit-btn', class: 'btn btn-primary'

- if @member.persisted?
  hr
  = link_to '削除する' , @member, data: { confirm: t('dictionary.message.destroy.confirm', resource_name: @member.real_name) }, method: :delete, class: 'btn btn-outline-danger'

app/views/members/edit.html.slim
h3.my-3 メンバー編集

= render 'form'

app/views/members/index.html.slim
h3.my-3 メンバー
.card.my-3
  .card-body
    = link_to new_member_path, id: 'new-btn', class: 'btn btn-outline-primary'
      | メンバー追加

    table.table.border-bottom.my-3
      thead.thead-light
        tr
          th
          th = Member.human_attribute_name(:handle_name)
          th = Member.human_attribute_name(:real_name)
          th = Member.human_attribute_name(:email)
          th = Member.human_attribute_name(:projects)
          th

      tbody
        - @members.each do |member|
          tr
            td.status
              - if member.retired
                span.badge.badge-dark 退職済み
            td.handle_name = member.handle_name
            td.real_name = member.real_name
            td.email = member.email
            td.projects = project_list(member)
            td
              = link_to '編集', edit_member_path(member), class: 'btn btn-outline-primary'

app/views/members/new.html.slim
h3.my-3 メンバー追加

= render 'form'